name: Build Extension

on:
  release:
    types: [published]

  workflow_dispatch:

env:
  REPOSITORY_NAME: ${{ github.event.repository.name }}
  EXTENSION_ID: fejaklhhhccnlcgnapejecfofkackgic

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build Extension
        run: yarn build

      - name: Zip Folder
        run: zip -jr ${{ env.REPOSITORY_NAME }}-${{ github.event.release.tag_name }}.zip ./extension/*

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          path: ${{ env.REPOSITORY_NAME }}-${{ github.event.release.tag_name }}.zip

      - name: Release to GitHub
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.REPOSITORY_NAME }}-${{ github.event.release.tag_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release to Chrome Web Store
        uses: mnao305/chrome-extension-upload@2.2.0
        with:
          file-path: ${{ env.REPOSITORY_NAME }}-${{ github.event.release.tag_name }}.zip
          extension-id: ${{ env.EXTENSION_ID }}
          client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          refresh-token: ${{ secrets.GOOGLE_REFRESH_TOKEN }}