name: Build Extension

on:
  create:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      
      - name: Build Extension
        run: yarn build

      - name: Zip Folder
        run: zip -r ${{ github.event.release.tag_name }}.zip ./extension/*

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          path: ${{ github.event.release.tag_name }}.zip