name: Build Extension

on:
  create:
    tags:
      - '*'

  workflow_dispatch:

env:
  REPOSITORY_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      
      - name: Build Extension
        run: yarn build

      - name: Zip Folder
        run: zip -r ${{env.REPOSITORY_NAME}}-${{ github.event.release.tag_name }}.zip ./extension/*

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          path: ${{env.REPOSITORY_NAME}}-${{ github.event.release.tag_name }}.zip
      
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{env.REPOSITORY_NAME}}-${{ github.event.release.tag_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}